version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - restaurant-network
  # Payment Service
  payment-service:
    build: ./payment-service
    container_name: payment-service
    restart: always
    ports:
      - "5009:5009"
    environment:
      - PORT=5009
      - MONGO_URI=
      - JWT_SECRET=270411
      - INTERNAL_API_KEY=0c1f4fa5cc7f7cd07686a6825e623aaba380cc09d08f69b0f13367a098d1a280
      - NODE_ENV=development
      - STRIPE_SECRET_KEY=
      - STRIPE_WEBHOOK_SECRET=
    volumes:
      - ./shared:/usr/src/app/shared
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5009/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - restaurant-network  # Delivery Service
  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    restart: always
    ports:
      - "5012:5012"
    environment:
      - PORT=5012
      - MONGO_URI=
      - JWT_SECRET=270411
      - INTERNAL_API_KEY=0c1f4fa5cc7f7cd07686a6825e623aaba380cc09d08f69b0f13367a098d1a280
      - NODE_ENV=development
      - ORDER_SERVICE_URL=http://order-service:5006
      - USER_SERVICE_URL=http://user-service:5002
    volumes:
      - ./shared:/usr/src/app/shared
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5012/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      mongo:
        condition: service_healthy
      user-service:
        condition: service_started
      order-service:
        condition: service_started
    networks:
      - restaurant-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=
      - JWT_SECRET=270411
      - INTERNAL_API_KEY=0c1f4fa5cc7f7cd07686a6825e623aaba380cc09d08f69b0f13367a098d1a280
      - NODE_ENV=development
    volumes:
      - ./shared:/usr/src/app/shared
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      mongo:
        condition: service_healthy
      user-service:
        condition: service_started
      restaurant-service:
        condition: service_started
    networks:
      - restaurant-network

  # User Service
  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=
      - JWT_SECRET=270411
      - INTERNAL_API_KEY=0c1f4fa5cc7f7cd07686a6825e623aaba380cc09d08f69b0f13367a098d1a280
      - NODE_ENV=development
      - ORDER_SERVICE_URL=http://order-service:5006
    volumes:
      - ./shared:/usr/src/app/shared
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - restaurant-network

  # Restaurant Service
  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    restart: always
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGO_URI=
      - JWT_SECRET=270411
      - INTERNAL_API_KEY=0c1f4fa5cc7f7cd07686a6825e623aaba380cc09d08f69b0f13367a098d1a280
      - NODE_ENV=development
      - USER_SERVICE_URL=http://user-service:5002
      - ORDER_SERVICE_URL=http://order-service:5006
      - MENU_SERVICE_URL=http://menu-service:5004
      - SEARCH_SERVICE_URL=http://search-service:5010
    volumes:
      - ./shared:/usr/src/app/shared
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      mongo:
        condition: service_healthy
      user-service:
        condition: service_started
    networks:
      - restaurant-network

  # Menu Service
  menu-service:
    build: ./menu-service
    container_name: menu-service
    restart: always
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - MONGO_URI=
      - JWT_SECRET=270411
      - INTERNAL_API_KEY=0c1f4fa5cc7f7cd07686a6825e623aaba380cc09d08f69b0f13367a098d1a280
      - NODE_ENV=development
      - SEARCH_SERVICE_URL=http://search-service:5010
    volumes:
      - ./menu-uploads:/usr/src/app/uploads
      - ./shared:/usr/src/app/shared
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - restaurant-network

  # Cart Service
  cart-service:
    build: ./cart-service
    container_name: cart-service
    restart: always
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - MONGO_URI=
      - JWT_SECRET=270411
      - INTERNAL_API_KEY=0c1f4fa5cc7f7cd07686a6825e623aaba380cc09d08f69b0f13367a098d1a280
      - NODE_ENV=development
      - MENU_SERVICE_URL=http://menu-service:5004
    volumes:
      - ./shared:/usr/src/app/shared
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      mongo:
        condition: service_healthy
      menu-service:
        condition: service_started
    networks:
      - restaurant-network

  # Order Service
  order-service:
    build: ./order-service
    container_name: order-service
    restart: always
    ports:
      - "5006:5006"
    environment:
      - PORT=5006
      - MONGO_URI=
      - JWT_SECRET=270411
      - INTERNAL_API_KEY=0c1f4fa5cc7f7cd07686a6825e623aaba380cc09d08f69b0f13367a098d1a280
      - NODE_ENV=development
      - USER_SERVICE_URL=http://user-service:5002
      - RESTAURANT_SERVICE_URL=http://restaurant-service:5003
      - MENU_SERVICE_URL=http://menu-service:5004      - CART_SERVICE_URL=http://cart-service:5005
      - NOTIFICATION_SERVICE_URL=http://notification-service:5008
      - TABLE_SERVICE_URL=http://table-service:5007
    volumes:
      - ./shared:/usr/src/app/shared
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      mongo:
        condition: service_healthy
      user-service:
        condition: service_started
      restaurant-service:
        condition: service_started
      cart-service:
        condition: service_started
    networks:
      - restaurant-network

  # Table Service
  table-service:
    build: ./table-service
    container_name: table-service
    restart: always
    ports:
      - "5007:5007"
    environment:
      - PORT=5007
      - MONGO_URI=
      - JWT_SECRET=270411
      - INTERNAL_API_KEY=0c1f4fa5cc7f7cd07686a6825e623aaba380cc09d08f69b0f13367a098d1a280
      - NODE_ENV=development
      - RESTAURANT_SERVICE_URL=http://restaurant-service:5003
    volumes:
      - ./shared:/usr/src/app/shared
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5007/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      mongo:
        condition: service_healthy
      restaurant-service:
        condition: service_started
    networks:
      - restaurant-network

  # Notification Service
  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: always
    ports:
      - "5008:5008"
    environment:
      - PORT=5008
      - MONGO_URI=
      - JWT_SECRET=270411
      - INTERNAL_API_KEY=0c1f4fa5cc7f7cd07686a6825e623aaba380cc09d08f69b0f13367a098d1a280
      - NODE_ENV=development
      - USER_SERVICE_URL=http://user-service:5002
    volumes:
      - ./shared:/usr/src/app/shared
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5008/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      mongo:
        condition: service_healthy
      user-service:
        condition: service_started
    networks:
      - restaurant-network

  # Search Service
  search-service:
    build: ./search-service
    container_name: search-service
    restart: always
    ports:
      - "5010:5010"
    environment:
      - PORT=5010
      - MONGO_URI=
      - JWT_SECRET=270411
      - INTERNAL_API_KEY=0c1f4fa5cc7f7cd07686a6825e623aaba380cc09d08f69b0f13367a098d1a280
      - NODE_ENV=development
      - RESTAURANT_SERVICE_URL=http://restaurant-service:5003
      - MENU_SERVICE_URL=http://menu-service:5004
      - ENABLE_SYNC_JOBS=true
    volumes:
      - ./shared:/usr/src/app/shared
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      mongo:
        condition: service_healthy
      restaurant-service:
        condition: service_started
      menu-service:
        condition: service_started
    networks:
      - restaurant-network

  # User Activity Service
  user-activity-service:
    build: ./user-activity-service
    container_name: user-activity-service
    restart: always
    ports:
      - "5011:5011"
    environment:
      - PORT=5011
      - MONGO_URI=
      - JWT_SECRET=270411
      - INTERNAL_API_KEY=0c1f4fa5cc7f7cd07686a6825e623aaba380cc09d08f69b0f13367a098d1a280
      - NODE_ENV=development
      - USER_SERVICE_URL=http://user-service:5002
      - ORDER_SERVICE_URL=http://order-service:5006
      - RESTAURANT_SERVICE_URL=http://restaurant-service:5003
    volumes:
      - ./shared:/usr/src/app/shared
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5011/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      mongo:
        condition: service_healthy
      user-service:
        condition: service_started
      order-service:
        condition: service_started
      restaurant-service:
        condition: service_started
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge

volumes:
  mongo-data:
