apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  mongo-uri: ""
  jwt-secret: "270411"
  internal-api-key: "0c1f4fa5cc7f7cd07686a6825e623aaba380cc09d08f69b0f13367a098d1a280"
